# Site settings
title: Ruthless Programming 
email: william@ruthlessprogramming.com
description: > # this means to ignore newlines until "baseurl:"
    This is a blog based on Android Development, however you can expect to see content covering a wide range of issues. Of particular interest is alternative JVM languages such as Kotlin,  implementation guidance and how to tutorials for beginners and developers at large
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ruthlessprogramming.com" # the base hostname & protocol for your site
twitter_username: parrishdev    
github_username:  wrparrish

# Build settings
markdown: kramdown


